# Generated by Django 5.1.2 on 2024-10-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('Name', models.CharField(max_length=15)),
                ('AdhaarNo', models.IntegerField(primary_key='AdhaarNo', serialize=False)),
                ('LoanAmt', models.IntegerField()),
                ('DOB', models.DateField()),
                ('Email', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
