# Generated by Django 5.1.2 on 2024-10-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='AdhaarNo',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='LoanAmt',
        ),
        migrations.AddField(
            model_name='bank',
            name='AccountNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bank',
            name='AdhaarNumber',
            field=models.IntegerField(default=0, primary_key='AdhaarNumber', serialize=False),
        ),
        migrations.AddField(
            model_name='bank',
            name='LoanAmount',
            field=models.IntegerField(default=0),
        ),
    ]
