# Generated by Django 5.1.2 on 2024-10-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0002_remove_bank_adhaarno_remove_bank_loanamt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
